export default [
  'Reflect on who you are in each moment that arises.',
  'Take a moment to reflect on your understanding of what it means to be free.',
  'Pay close attention to your breath in each moment that arises.',
  'Listen the sounds around you without trying to understand, label or hold on to them as time passes through you.',
  'Feel the shape of your whole body.',
  'Take a moment to scan your body for areas that may hold tension.',
  'What does the inside of your hand feel like? Pay close attention to it without labelling.',
  'Make the movements of firing a bow and arrow without making any effort at all.',
  'Are you making an effort to do something right now? Continue what you are doing but without effort.',
  'Pay attention to your jaw. Is it clenched or relaxed?',
  'Pay attention to your shoulders. Are they tense or relaxed?',
  'Think of someone whom it is easy to feel love for. Wish that person well.',
  'Think of the last interaction you had with someone whose name you did not know. Wish this person happiness.',
  'Look around and imagine your mind as a mirror. Holds no image, do not judge or anticipate. Just observe.',
  'Reflect on your understang of what it means to be liberated.',
  'In your mind, say the word “watermelon” without attaching any meaning to it.',
  'What is the earliest memory you have?',
  'Extend your arms apart and bring your hands together as slowly as you can.',
  'Surrender.',
  'Take a deep breath.',
  'Read these words but do not attach meaning to them.',
  'The objective is not to rid oneself of ego but rather to rid oneself of identification with ego.',
  'Just be here now.',
];
